const TICK_DURATION = 1000 / 30;
const INITIAL_DELAY = 8 * TICK_DURATION;
const INIT_DURATION = 5 * TICK_DURATION;
const FLICKER_DURATION = 40 * TICK_DURATION;

const DEFAULT_EASING = 'ease-in-out';

export {
  DEFAULT_EASING,
  FLICKER_DURATION,
  INITIAL_DELAY,
  INIT_DURATION,
  TICK_DURATION,
};