const TICK_DURATION = 1000 / 30;
const INITIAL_DELAY = 8 * TICK_DURATION;
const INIT_DURATION = 5 * TICK_DURATION; // also DEINIT_DURATION
const CASCADE_DELAY = 1 * TICK_DURATION; // 1
const SLIDE_IN_DURATION = 5 * TICK_DURATION; // 9
const FLICKER_DURATION = 40 * TICK_DURATION;
const FILL_BAR_DURATION = 12 * TICK_DURATION;

const DEFAULT_EASING = 'ease-in-out';
const FILL_BAR_EASING = 'cubic-bezier(0.27, 1.13, 0.88, 0.96)';

const BAR_FONT_SIZE = 18;
const BAR_HEIGHT = 42;
const THICK_LINE_WIDTH = 10;
const THIN_LINE_WIDTH = 3;

export {
  BAR_FONT_SIZE,
  BAR_HEIGHT,
  CASCADE_DELAY,
  DEFAULT_EASING,
  FILL_BAR_DURATION,
  FILL_BAR_EASING,
  FLICKER_DURATION,
  INITIAL_DELAY,
  INIT_DURATION,
  SLIDE_IN_DURATION,
  THICK_LINE_WIDTH,
  THIN_LINE_WIDTH,
  TICK_DURATION,
};
