menu:
    About: /about/
    Blog: /
    Archive: /archives/
    Projects: /projects/
    GitHub: https://github.com/romebop

favicon: /gitlogo.png
logo: /favicon.png

# Comment
# e.g disqus: seansun

# Analytics
# google-analytics:

# Copyright Infomation
startyear: 2016

# Font CDN
#true : use google fonts api, not stable for chinese visitor sometimes, caused by force majeure factor
#false: use useso fonts api instead of google's, great response speed for chinese visitor
googlefonts: true
